### ISSUE TITLE
Miss Decal Scale

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#100]
@joohwankimNV has requested the ability to scale the (miss) decals used in the application. Questions to answer include:

1. Do we want to do this globally (i.e. for a whole experiment) or on a session-basis?
_Preliminary Answer_: We'd like it to change on a per-session basis.

2. Do we want this attached to the weapon being used?
_Preliminary Answer_: We'd like it to be a property of the weapon.

3. Do we want to scale anything else while we do this (i.e. the projectile)?
_Preliminary Answer_: Not for now.

Let me know if any/all of the info above is correct/if not what to change and I will move forward with developing this feature.

**Comment by bboudaoud-nv** [comment]
An early implementation of this has now been developed. You can use the `decalScale` parameter within the `weapon` config to set a scale to apply to the decals (`1.0` means default sizing).

@joohwankimNV feel free to try this out and let me know how it works.

**Comment by joohwankimNV** [comment]
Agree with all the preliminary answers provided. Thank you! I am taking a look shortly.

**Comment by joohwankimNV** [comment]
Great! Thank you very much. Closing..
