### ISSUE TITLE
renderMuzzleFlash/muzzleOffset doesn't do anything

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#106]
Currently the [`renderMuzzleFlash` and `muzzleOffset` parameters](https://github.com/NVlabs/abstract-fps/blob/master/docs/weaponConfigReadme.md#muzzle-flash-control) for the weapon config don't actually control anything (that I can see) in the app. 

Do we want to add support for muzzle flash or consider just removing these flags entirely? If we would like to add support, let's work out the approach in the design document.

**Comment by bboudaoud-nv** [comment]
A [recent commit](https://github.com/NVlabs/abstract-fps/commit/d993810e8088769aa79774c7d1fabaa45810208e) to the `BulletExplosionParams` branch resolves this issue with the suggested fix of commenting out the unused parameter/documentation.

**Comment by jspjutNV** [comment]
Did close pull request #105 resolve this issue? If so I think we can close this one.

**Comment by bboudaoud-nv** [comment]
Yes, pull request #105 closes this issue (commented out the feature for now).
