### ISSUE TITLE
Weapon hitDecal doesn't show when in non-hitscan mode

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#107]
Hit decals do not appear to be showing up correctly when in non-hitscan mode. This may be due to different behavior when in non-hitscan mode.

**Comment by bboudaoud-nv** [comment]
A quick fix for this was added as of [this commit](https://github.com/NVlabs/abstract-fps/pull/105/commits/2fb103d34747c9e3370cc2b4474711ad710aca02). However, hit decals should (likely) be specified on a per-target basis to allow for flexibility of size/image/time shown relative to the target geometry.

I plan to keep this issue open for discussion for now.

**Comment by bboudaoud-nv** [comment]
Thinking about this more the hit decal is really a function of the weapon _and_ the target (at least this is the real world model for hit decals). For example, the "sparks" created when a projectile hits a target are a function of both the projectile _and_ target materials.

- Configuring this per weapon makes sense since a particular weapon would likely create a particular "hit effect" on the target (same as miss decals).
- Configuring this per target also makes sense in that a particular hit decal might not show up well against/around a particular target geometry.

For now I'm tempted to leave this with the weapon, but I'm curious what others think. We could always do a cascaded model wherein the weapon specifies the default hit decal, then targets can modify their (individual hit decal) from here, but this would mean a weapon change would only impact target that didn't specify a hit decal.

**Comment by jspjutNV** [comment]
Maybe we do a simplified model where both the target and the weapon can specify independent effects. Both would happen, but the weapon effect can happen on both targets as well as arbitrary hits in the scene geometry, but the target effect only happens on the target. Are there particular situations where these 2 specifications would be a problem?

**Comment by bboudaoud-nv** [comment]
Pull request #105 solves most of this issue, but doesn't close the problem of target-based hit decals.

**Comment by bboudaoud-nv** [comment]
I'm going to close this issue (since it's labeled as "bug") and have opened a new issue (Issue #123) for a possible target-based decal enhancement.
