### ISSUE TITLE
Spawning Targets

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#11]
There are multiple mechanisms by which to spawn targets (primarily in [App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp) in the application right now. It is not entirely clear to a new user which are actually being used. There are also several TODO comments indicating we were planning to move towards @morgan3d's approach to target motion but didn't have time before our first study. Do we want to do this now? Should we remove the unused methods? Should we unite how targets are spawned into a single routine?

**Comment by bboudaoud-nv** [comment]
Currently [App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp) has multiple methods for spawning targets:

- [`spawnParameterizedRandomTarget()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L117)
- [`spawnRandomTarget()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L171)
- [`spawnTarget()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L219)
- [`spawnFlyingTarget()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L247)
- [`spawnJumpingTarget()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L284)

Of these, only the last 2 are actually called when `playMode = true`. We should consider uniting/documenting/removing these to help make things clearer, but I'm not sure which contains our desired approach.

**Comment by jspjutNV** [comment]
Overview of these methods and where they came from.

* `spawnTarget()`: the core function to spawn a target. Was designed when there was 1 target type and was intended to be called everywhere when we wanted to spawn a target.
* `spawnRandomTarget()`: the second function, hooked up to the developer UI which demonstrates how to attach a motion path to a new target. Intended for developer use only.
* `spawnFlyingTarget()`: a fork of `spawnTarget()` renamed to represent the `FlyingTarget` object that evolved from our old single target type. I believe this is the one currently used in experiments.
* `spawnJumpingTarget()`: similar to the `FlyingTarget` one, but for the `JumpingTarget` type that was added later in development.
* `spawnParameterizedRandomTarget()`: I started writing this to provide an interface that matched the experiment configuration that would create a motion path the same way as in `spawnRandomTarget()` but matching the types of motion decisions that are found inside `FlyingTarget` now. This is not currently used, but if someone decides to move to the pre-computed motion path model, we could replace this function with the correct code.

I don't think anything needs to be done with these right now, but maybe it would be good to open another bug to fix `spawnParameterizedRandomTarget()`

**Comment by bboudaoud-nv** [comment]
@jspjutNV  take a look at issue #13 for more specific details on `spawnParametrizedRandomTarget()`. I agree that we can probably leave multiple target spawning mechanisms available in code even if they are not called. These functions should be well-documented in source/readme's to make this more obvious to the developer.

**Comment by bboudaoud-nv** [comment]
Since there seems to be no strong preference for removing these here, I am going to close this issue. We can continue more specific discussions in issues like #25, #12, and #13.
