### ISSUE TITLE
Likely memory leak with floating combat text

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#112]
If this requires code changes it should probably wait until after #111 gets merged in to be fixed.

In preparing #111 I noticed that while FloatingCombatText fades itself out over time, I don't believe it deletes itself from the scene graph. This means that when enabled, floating combat text may cause performance to slowly degrade as more text is added. To confirm this, you can check the number of combat text entries in the scene over time.

**Comment by bboudaoud-nv** [comment]
The floating combat text removal approach is a bit complicated, but seems to be working here. 

Around line 893 of App.cpp we look for text where the timer has expired (this could be moved to sdt-based) and null all pointers in the `m_combatTextList` array with expired timers. We then call `m_combatTestList.removeNulls()` after the check loop to clear these instances.

As of now it does not seem that this array grows unbounded, though (as mentioned above) we could move to simulation time (sdt) as opposed to a wall-clock timestamp approach.

**Comment by jspjutNV** [comment]
I agree with the description and that it works without a memory leak, so I'm going to close this issue.
