### ISSUE TITLE
`App::onSimulation` calls `scene()->onSimulation` twice

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#113]
In `App::onSimulation` in `App.cpp` this line happens twice in a row, but should only happen once.

```if (scene()) { scene()->onSimulation(sdt); }```

While the code fix for this is straightforward, I want to open this issue first to allow discussion to make sure everyone is ready for the fix once we deploy it.

**Comment by jspjutNV** [comment]
The effect of this bug is that everything being simulated by the scene is effectively running twice as fast as intended. I tested removing the duplicate line and it seemed like all target motion was half as fast, which would mean experiments would need to be redesigned.

**Comment by bboudaoud-nv** [comment]
This issue was closed by the merge of #119.
