### ISSUE TITLE
Commented out spawnTarget() call

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#12]
At [line 93 of `App.cpp`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L93) there are two commented out calls to `spawnTarget()`.

  `//spawnTarget(Point3(37.6184f, -0.54509f, -2.12245f), 1.0f);`
  `//spawnTarget(Point3(39.7f, -2.3f, 2.4f), 1.0f);`

Since this isn't how targets are spawned in the actual application we might want to remove them. This is affiliated with issue #11.

**Comment by jspjutNV** [comment]
These are currently at lines 80-81, but I believe it's safe to remove these unless there's something special about these spawn locations for future testing. In any case, those locations are saved with this issue now, so we should be able to easy find them again.

**Comment by bboudaoud-nv** [comment]
Per @jspjutNV's suggestion I've removed these as of a [recent commit](https://github.com/NVlabs/abstract-fps/commit/258bc1394ab8a6dbc6b2f1f60dcc54e9ccdc519e).
