### ISSUE TITLE
spawnParameterizedRandomTarget()

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#13]
The `spawnParameterizedRandomTarget()` method is implemented but not called in [`App.cpp`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L129). Should we be moving to use of this method or removing it? This is related to issue #11.

**Comment by jspjutNV** [comment]
As I said in #11 , this function currently doesn't work correctly, but I believe we'd still like to fix it some time. Let's keep this bug open with low priority since it's not blocking progress at the moment.

**Comment by jspjutNV** [comment]
To clarify some more, the way this should work is that it should spawn a target with the provided parameters which includes pre-computing the motion path for the given target with the provided motion parameters. It should match the specifications detailed by the Target/trial configurations

**Comment by jspjutNV** [comment]
Considering the massive changes that have been made to our target types and the way targets are spawned at the moment, I believe this issue should be closed as it's no longer really relevant. 

I'm going to open a pull request that removes the commented out and unused target spawning functions.
