### ISSUE TITLE
Run arbitrary commands from FPSci

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#148]
Currently the FPSci solution is hard-coded to run the research latency logger platform around start of sessions. We have a request to support running others scripts/programs instead. It makes sense to consider adding fully configurable command calls around FPSci runtime for diverse experimenter needs. 

This would/could include running arbitrary commands before/after the start of an application, session, block, or even trial. We should discuss which fields are useful and consider adding those fields which would be most helpful.

**Comment by bboudaoud-nv** [comment]
The design I'm currently considering is as follows:

*In the startup config:* 
- (Optionally) specify a `runAtStart` and `runAtClose` command string for the entire application

*In the session/experiment config (FpsConfig):*
- (Optionally) specify a `runOnSessionStart` and `runOnSessionEnd` command string
- (Optionally) specify a `runOnTrialStart` and `runOnTrialEnd` command string

If there are more options we should include let me know and I'd be happy to include these as well.

**Comment by jspjutNV** [comment]
It seems like the intent is for these variables to specify a command line to execute at each stage. Maybe calling them `command` instead of `run` would be more intuitive. For example, you could have:
```commandOnStart = "startLog.sh";
commandOnSessionStart = "compress_data.py *.db; rm *.db";
commandOnEnd = "cleanup.sh";```

**Comment by bboudaoud-nv** [comment]
I'm okay with the new naming and will update the [branch](https://github.com/NVlabs/abstract-fps/tree/RunCommands) accordingly.

I like the idea of lists of commands for exactly the reason you've described. In a previous post, I described using a combination shell script to handle multiple commands/error reporting, but allowing support for Array's of commands seems like a simple enough feature to implement.

**Comment by bboudaoud-nv** [comment]
Another problem to think about here is the difference between blocking and non-blocking behavior in these commands. If we assume the command "runs to completion" fairly quickly we don't need to store process handles and explicitly kill processes at the end of a session/trial.

This is particularly true when a trial/session start command is run in close proximity to the previous trial/session's end command and may share common data.

**Comment by jspjutNV** [comment]
Oh yeah... I totally forgot that. Putting multiple commands in a single string would allow the user to explicitly sequence the execution of those commands, but would do nothing about ensuring they complete before the end of the run of FPSci or before the next command in the list of strings is started. I think the spec we assume here is all of these commands should be asynchronous, but that means you could get bad behavior if you try to do thing like `rm *.db` like I suggested in my example...

**Comment by bboudaoud-nv** [comment]
We should agree on a model for how commands will be supported in this approach. I'm fine with supporting a single command or multiple commands, but how this interacts with long running processes/processes that need to be explicitly ordered/closed is still TBD. I'm fine with any solution but think we should agree on the initial supported features and evolve this support from there.

My initial proposal is that we support an (ordered) list/array of commands per session, but don't enforce each process ends before the next begins within this list (i.e. they are all launched "together"). Any strictly serialized commands can be called as a shell script/provided as a delimited string.

The idea being that by doing this the user will be less likely to use processes that might spawn additional processes that we can't close from in-app (using the process handle).

For now I'm fine with sending a close request to the process handle whenever we move trial-to-trial/session-to-session.

**Comment by pknowlesnv** [comment]
Is this for a command to be running in the background during the session and killed at the end or to have the external command set up some external state, e.g. change system clocks before each session?

Both could be possible if the scripts run to completion immediately - the pre-session script could start some background process and the post-session script could stop it. Could just be a system() call, which blocks. This would be nice for log post processing, just in case it's slow and starts reading the log for the next session or something like that. You could also pass the session ID or various other arguments. For more advanced stuff (like allowing the main loop to keep rendering) maybe use `libexecstream` or some equivalent but until a feature is needed, system() will be easier. One script could invoke many others.

**Comment by bboudaoud-nv** [comment]
This is intended to allow both cases (background and short running tasks), but can be tricky to support. 

Currently we are using `CreateProcess()` calls to launch (non-blocking) background tasks and rely on the user to provide end of trial/session commands that close themselves (or are otherwise orphaned). We kill all "start" tasks using their process handle before starting to run the "end" tasks for sessions/trials.

In the future it might make sense to use `system()` calls for the end of trial events, or allow the user to configure whether commands block or run in the background on a per-command basis.
