### ISSUE TITLE
Allowing Player Motion

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#15]
Allowing in-app player motion is simple enough to add to the [`experimentconfig.Any`](https://github.com/NVlabs/abstract-fps/blob/master/target/data-files/experimentConfigReadme.md) file, but may have other impacts on the application. Namely we should look into how this impacts spawning/moving targets. This could likely be tested in `playMode` = `False`.

**Comment by bboudaoud-nv** [comment]
@jspjutNV has indicated this will not be hard to enable (look at use of  `setMoveRate()` in [line 123 of App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L123) though avoiding issues w/ targets in walls is another story. We should also vet whether or not `m_userSettingsMode` is being used correctly here (allows you to move even when `playMode = True` up until you close the tab menu for the first time.

**Comment by bboudaoud-nv** [comment]
[A recent commit](https://github.com/NVlabs/abstract-fps/commit/b0e0e4ddd29c6e880494be77934fbad3d0ea3737) updates the GUI for `playMode=False` to allow player motion based on a checkbox. The speed of player motion is not yet controllable. This should also resolve the bug in issue #19.

**Comment by jspjutNV** [comment]
Let's make player motion controllable as @bboudaoud-nv suggests by having an experiment config parameter that controls the motion speed. We could also expose that value in the devMode GUI (`playMode=False`).

**Comment by bboudaoud-nv** [comment]
I've added a `moveRate` parameter to the [experiment config file](https://github.com/NVlabs/abstract-fps/blob/master/target/data-files/experimentConfigReadme.md) as of a [recent commit](https://github.com/NVlabs/abstract-fps/commit/75c934d143adea0782c2cffde17f1b9269355b9b).

This now allows designers to set the player move rate in m/s. There are now multiple issues related to when `moveRate != 0`. For example the player can now spawn, then move past targets, effectively "losing" them in the scene. In addition, since no collision detection with the scene is enabled, the player can easily move through walls/spawn targets behind them. We should consider what sort of minimal subset of features we will need to implement to get this movement mechanic working well/true to the typical FPS experience. Maybe we should create a new issue to track this development.

**Comment by bboudaoud-nv** [comment]
Should we add a GUI field to `playMode = false` to allow the user to dynamically control the move rate while in-game?

**Comment by bboudaoud-nv** [comment]
A [recent commit](https://github.com/NVlabs/abstract-fps/commit/a5e073acdb7eead780bfdd71a32c7225ec1b24f3) adds support for this in developer mode (`playMode = false`). I'm going to leave this issue open since its original "problem statement" includes things like target motion not being dynamic to the added player motion.

**Comment by bboudaoud-nv** [comment]
Let's close this issue for now and create a new issue for target motion not being responsive to player motion, as this is another issue altogether
