### ISSUE TITLE
Question prompts are poorly placed

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#158]
When a question prompt is shown (see example config below), the menu opens in a weird spot off to the left of the screen. Compared to the user config menu, it's hard to notice this prompt. Given that the user is expected to provide feedback, I recommend we set the response menu to the center of the screen on top of the user config menu. 

It may also make sense to size the question menu to completely cover the user config menu, and have the question response close all menus to resume the experiment.

```
    sessions = ( 
        {
            description = "Question 1"; 
            frameRate = 120; 
            id = "Q1"; 
            settingsVersion = 1; 
            trials = ( { count = 0; ids = ( ); } );
            questions = {
                {
                    type = "MultipleChoice",
                    prompt = "Left or Right",
                    options: ["Left", "Right"],
                }
            };
        } ); 
```
![image](https://user-images.githubusercontent.com/26633010/84522053-ef244600-aca3-11ea-8d3f-170f5719e1ca.png)

**Comment by bboudaoud-nv** [comment]
Currently adding any questions to the end of the session enforces opening up the user menu, is this behavior desirable? 

Considering the change we made for issue #153, do we want to make opening the user menu conditional on the  `showMenuBetweenSessions`?

**Comment by jspjutNV** [comment]
I think it would be best to not show the user settings menu unless the user explicitly requests it with the menu button.
