### ISSUE TITLE
"Change User" button should save the status

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#160]
When you click the "Change User" button in the user menu the user changes temporarily, but the change isn't saved to the user config. When this button is pressed, I believe that change should be reflected in either the user config, or maybe the currently active user should actually be in the user status instead (where we track progression through an experiment).

**Comment by bboudaoud-nv** [comment]
Interestingly, it appears the only place that the user config is saved is when a new one is created (i.e. in `UserTable::load()`. When this does happen it does not use the `userConfigPath` variable from the startup config (as it should).

This makes me think that we don't ever write back the `currentUser` field from within the application (though we do update it in memory when the update user button is pressed).

My suggestion is that we:
1. Update the `UserTable::load()` routine to use the correct path for writing defaults
2. Update the `UserMenu::updateUserPress()` to write the updated user status to disk

**Comment by jspjutNV** [comment]
Does it makes sense to move the current user to the user status instead of keeping it in the user config? I know that's a pretty large change, but it seems to make more sense because the user status is written frequently and automatically, but the user config is only written when the user hits the save button.
