### ISSUE TITLE
Improve end-of-session question system

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#167]
This is a general request to capture requests around the in application system for dialog-based user feedback. Comments include:

* Add support for radio-button style prompts with a "Submit" button
* Add support for multiple questions in a single pop-up menu
* Add minimal validation for question responses

These changes might be replaced with a possible web form-based solution (i.e. Google Forms) if opening/displaying such an option from #in-app is available.

**Comment by bboudaoud-nv** [comment]
As an alternative we can try opening a google form via a end of trial/session command. I'm not sure this will open in the foreground, but might be a good alternative to building a full menu system in FPSci.

**Comment by bboudaoud-nv** [comment]
The improved command specification supported in #202 allows the ability to open a foreground google forms page as a way to automate this process. I suggest we close this issue by supporting more complex questions via a call out to the web browser:

```
commandsOnSessionEnd = [ { command = "cmd /c start [forms URL]", foreground = true} ];
```

**Comment by bboudaoud-nv** [comment]
@joohwankimNV with #202 merged into master we should be able to support using a web-based system (i.e. Google Forms) to collect feedback from users. If you agree this is sufficient we can close this issue.

**Comment by joohwankimNV** [comment]
I agree to close this.
