### ISSUE TITLE
Visual C++ Redistributable Install Required

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#171]
Users who don't already have it installed need to install [Microsoft's Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) in order to run FPSci. To make this easier, the following should be done:

- [x] Document this requirement in the repository `readme.md`
- [x] Provide a simplified readme to embed in the distribution with those instructions

Optionally, if we can find a way to detect the specific error on startup, the error message could direct the user to the appropriate website to download the installer.

For reference, the error reported is the following:

> VCRUNTIME140_1.dll was not found.

**Comment by bboudaoud-nv** [comment]
This makes sense, I would lean in the direction of linking a new `distributionReadme.md`, or some other file that is intended to specifically describe using packaged distributions of FPSci, in the top-level readme as opposed to producing a full requirements list in the top-level `readme.md`.

**Comment by jspjutNV** [comment]
I ended up having the `fpsci_packager_generator.py` script generate a `README.txt` (at the end of the script) which it places in the root of FPSci. The packager then knows to copy that generated file to a distribution.
