### ISSUE TITLE
Interaction between showing user menu and running commands

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#178]
Behavior of commands run in the application introduced by #152 seems to interact with the `showMenuOnStartup` and `showMenuBetweenSessions` parameters in the config.

In some cases it appears only 1 of a list of commands are run, in others it seems as if the full list of commands is run multiple times. Placing breakpoints around the launching of commands does seem to impact this behavior.

Particularly missing/double command execution seems to happen around certain configurations of when to show the user menu. We should thoroughly test specifying `showMenuOnStartup` and `showMenuBetweenSessions` at the session/experiment level with single/multiple start of trial/session commands. We should verify both that all commands are run and that they are run the expected number of times.

**Comment by bboudaoud-nv** [comment]
This may have been resolved by setting the new command sub-flag `blocking = true` in the config file. I was able to "fix" some strange behavior by setting this blocking flag for my simple test commands.

**Comment by jspjutNV** [comment]
I agree that the `blocking = true` option for command configs added by #202 seems likely to fix this issue. I'm closing this one, but if someone notices this issue again, we can reopen this.
