### ISSUE TITLE
Require click to advance from scoreboard state

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#179]
@joohwankimNV has requested an option to require a user click in the scoreboard state before advancing the state machine within the session. I'm opening this issue so we can discuss and decide how this feature should be implemented.

**Comment by bboudaoud-nv** [comment]
I think the "easiest" path forward is to allow the user to set `scoreboardDuration` to -1 to indicate that a player click is required to move past the scoreboard in each session. This avoids adding a new flag that invalidates the `scoreboardDuration` set in the config. 

Of course, if we take this approach we should document this setting in the general config readme.

**Comment by jspjutNV** [comment]
The idea is that there will be both a duration that the user must wait, plus a click giving the user the option to delay as long as desired. So we need to be able to set the duration independently from the click flag. I suppose this flag could be the sign bit on the number, but I'm not sure if `-0` will set the value correctly. If we actually want these options independent, I think we'll need to add a `scoreboardRequireClick` boolean as well with the default likely being true.

The reason for this is to avoid a user accidentally clicking again at the end of a session before they realize that the score is displayed. I feel like the 5 s default `scoreboardDuration` is probably longer than needed for when `scoreboardRequireClick` is set to `true`. I'd suggest 1 second is probably long enough when `scoreboardRequireClick` is true. We should probably also discuss whether the required click should default to true or false. 

I suppose there's also the question of whether the designer should be allowed to set which key bind is used for this.

**Comment by bboudaoud-nv** [comment]
I believe I misunderstood, if the idea is to support a minimum duration _and_ a required click then an additional flag makes sense. If we all agree to this approach I believe a `scoreboardRequireClick` boolean flag makes the most sense.

Historically we would have had the default value be `false` to make behavior match what was previously in place, but I'm happy to use a different default value in this case.

If we let the user bind an arbitrary key for this then I suggest we move away from the term "click" in the descriptor. I'm fine with making this a hard coded button press for now and adding a key mapping later if requested.

I believe there is also a requirement for a left mouse click (mouse button up event) which is not key mapped to start the session, so if we do add a binding maybe we should use this for both events?

**Comment by bboudaoud-nv** [comment]
Also adding a note here, it looks like we don't currently serialize `scoreboardDuration` to any along with the other timing parameters. We can probably add that as part of this request.
