### ISSUE TITLE
Required description ("training") for per trial feedback message

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#185]
Currently there is a hard-coded test for a session's `description` field being _exactly_ "training" in the `Session::processResponse()` code. This results in the per trial success/failure messages only being shown when a session's description is "training".

I suggest that we:
1. Make whether this/other messages is/are shown experiment designer configurable
2. Consider a restructuring of how training sessions are implemented (in a new issue)
3. Document this option formally (in whatever form it takes)

This issue is designed to track a solution for (or continued use of) the hard-coded "training" string in `Session::processResponse()`. A new issue should be created to track any new explicit training-session support.

**Comment by jspjutNV** [comment]
I think @joohwankimNV might want to weigh in. It seems like showing or hiding success/failure messages should be controlled through an explicit flag and not through a string like you describe here.

**Comment by bboudaoud-nv** [comment]
@jspjutNV I agree that having explicit support for a `training` mode that can be set with a flag on a per-session basis makes a good deal of sense. If we agree on this I'd be happy to add support for it based around a new issue.
