### ISSUE TITLE
Automation for experiment-specific distribution/packages

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#188]
#172 improved the distribution process for the generic FPSci, but people working on experiments would like to be able to easily create a distribution intended for their specific experiment design. The important differences between the generic distribution and an experiment-specific distribution are captured below.

- Include the following files: `experimentconfig.Any`, `startupconfig.Any`, `userconfig.Any`, `userstatus.Any`
- Include additional data files used by the experiment.
- Include a special purpose `README.txt` written specifically for the experiment.

**Comment by bboudaoud-nv** [comment]
This feels like something that could be supported through the [`fpsci_packager_generator.py` file](https://github.com/NVlabs/abstract-fps/blob/master/scripts/package/fpsci_packager_generator.py) via a command line arguments(s). 

An `--include-configs` argument could be implemented to allow including the extra config files. The extra data-files list/readme could also be provided via argument, or just copied over/added to the output script manually after running the packager generator.

Alternatively, we could write a follow-up script to the package (generator) script that (by default) adds the configs to the packaged directory, and also copies over extra files/the `README.txt` file.
