### ISSUE TITLE
Release builds create `results` directory at the same level as FPSci

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#190]
It may be that we intend for this to happen, but instead of creating a `results` directory inside of the FPSci directory, FPSci creates a `results` directory parallel to the FPSci directory on release builds. I'm sure users can work around it, and I understand why it happens. Is this what we want to have happen or should we change the behavior?

**Comment by bboudaoud-nv** [comment]
My guess is we'd like to support the results/output directory as a field within the startup config to allow users to redirect this wherever they would like.

I believe the "problem" currently is that FPSci specifies `../results` as the results directory. When run in our normal structure this is relative to the `data-files` directory (thus the `FPSci` directory, or whatever parent name is used by the developer), but (I'm guessing) for packaged builds the `FPSci` directory likely contains the executable so it's the directory above that.

**Comment by jspjutNV** [comment]
Specifying the results directory in the experiment config seems like a good work around. I'd guess we'd want the default to be `results/` so that release build users will get an expected behavior out of it, and that developers who want to have the results appear outside of `data-files` will need to learn to specify `../results` as the path.
