### ISSUE TITLE
Startup config file name accessors assume particular naming/don't match docs

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#194]
The `experimentConfigPath` and `userConfigPath` don't currently work as described in the [`startupConfigReadme.md` file](https://github.com/NVlabs/abstract-fps/blob/master/docs/startupConfigReadme.md).

These paths were intended to direct the user to the user/experiment config _file_ rather than it's containing directory. It seems as though currently it is assumed the path variables provide the directory that the config files are located in (and that the files _must_ be named `experimentconfig.Any`, `userStatus.Any`, and `userConfig.Any`).

I'd suggest we revert to specifying the full file path (including the file name) from the startup config to allow experiment designers to use alternatively named config files. I also suggest we add a `userStatusPath` option to allow designers to set the user status path independent of that of the user config.

**Comment by bboudaoud-nv** [comment]
We should also consider adding the "system config" (i.e. latency logger config) here as well (though eventually it may just become a part of the experiment config).

**Comment by jspjutNV** [comment]
The `experimentConfigPath` and `userConfigPath` were originally designed to specify the path to the files, and not the filenames themselves. It looks like the documentation was incorrect and didn't represent the design. The idea being that someone could build an experiment with associated user configs, put it all in 2 directories, then swap to them easily by changing the path to those directories in the startup config.

I'd suggest `experimentConfigFilename` and `userConfigFilename` for this new functionality.

**Comment by bboudaoud-nv** [comment]
Agreed, will update the code to reflect this. We should also update our sample configs since the existing parameter names will no longer be valid.
