### ISSUE TITLE
Consider removing latency logger (system) config file

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#197]
We've already greatly reduced the use of system config to just the latency logger config parameters. @jspjutNV has made a good argument for moving away from it's use entirely in favor of experiment config parameters.

This issue is a place to discuss the idea of removing the latency logger/system config file in favor of our new command interface and possible some additional general config parameters.

**Comment by bboudaoud-nv** [comment]
There are 2 reasonable short-term options we can pursue here:

1. Move the existing logger flags (as-is) into the experiment config file (i.e. to general `FpsConfig` parameters). This would require minimal effort, and keep the functionality as-is.
2. Move to using the pre/post-session commands to support the latency logger. This might require adding support for some "find and replace" sub-strings that would allow the user to name their output file the same thing as is being used in the db filename and possible configure the logger COM port through another parameter.

The original intent of keeping these flags separate was the idea that systems would be more likely to have (or not have) this hardware support and experiments would specify it optionally. In practice most experiments have either required it or not.

**Comment by bboudaoud-nv** [comment]
Thinking about this more, I realize the original point of the system config file was to separate out system-specific config from experiment config. With this in mind, I'm tempted to leave a system config, but only provide the COM port names in this file.

Currently #203 would support adding these COM port names to generic commands in the experiment config using the supported substrings (`%loggerComPort` and `%loggerSyncComPort`).  

Alternatively we can just have per-machine experiment config files.

**Comment by jspjutNV** [comment]
I like having things in the system config that are exclusively machine specific and not related to the experiment design. The more an experiment config can be used across machines the better.

**Comment by bboudaoud-nv** [comment]
I've [added support for the system config back to the affiliated branch](https://github.com/NVlabs/abstract-fps/pull/203/commits/97ccfe8fc24a5d315fa14b47daeed2363ac09be7). We will want to carefully review this branch to make sure all the desired functionality is still there.
