### ISSUE TITLE
resetView()

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#20]
The `resetView()` method on [line 1257 of App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L1258) is not used and can be removed. Should we do this?

**Comment by jspjutNV** [comment]
I believe this was originally used to reset the view between trials, but we've moved to a model where player must hit a target at the neutral position to begin a new trial.

I think `resetView()` should be removed, but we'll want to discuss whether other forms of resetting the player may be useful features to add in the future.

**Comment by bboudaoud-nv** [comment]
Removed this method and the single (commented out) reference to it in a [recent commit](https://github.com/NVlabs/abstract-fps/commit/143c8521da86171b59c71193744355dbc8b5ea8f).
