### ISSUE TITLE
Consider renaming duration experiment config parameters for readability

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#205]
Currently there are 4 state-based durations affiliated with the experiment config:

* `readyDuration` -- Time before the start of each trial
* `taskDuration` -- Maximum time for user to complete a trial
* `feedbackDuration` -- Duration of feedback window between trials
* `scoreboardDuration` -- Duration of the feedback window between sessions

@joohwankimNV suggested we rename `scoreboardDuration` to `sessionFeedbackDuration` to improve clarity of the parameter. Accordingly I suggest we renamed `feedbackDuration` to `trialFeedbackDuration` to be consistent.

My suggested full renaming of these duration parameters is:

* `readyDuration` --> `pretrialDuration`
* `taskDuration` --> `maxTrialDuration`
* `feedbackDuration` --> `trialFeedbackDuration`
* `scoreboardDuration` --> `sessionFeedbackDuration`

This is a place to discuss this and other ideas for renaming the duration parameters.

**Comment by jspjutNV** [comment]
Seems like we could also rename the state machine states along with this config renaming.
