### ISSUE TITLE
Empty onCleanup()

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#21]
The `onCleanup()` method in [App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L1269) is empty/still included with just comments in the body. Should we leave this around or remove it?

**Comment by jspjutNV** [comment]
`onCleanup()` is standard for G3D `GApp`s. We should keep it around with an empty body unless there are things we've created in `onInit()` that need to be cleaned up, which we should clean up here.

**Comment by bboudaoud-nv** [comment]
The current comment in the body of `onCleanup()` is:

`// Called after the application loop ends.  Place a majority of cleanup code`
`// here instead of in the constructor so that exceptions can be caught.`

Could we improve this at all so that its clear to users what needs to be cleaned up/how exceptions should be handled. As a non-G3D developer this doesn't necessarily make sense to me as compared with a deconstructor.

**Comment by jspjutNV** [comment]
The [G3D Documentation](https://casual-effects.com/g3d/G3D10/build/manual/class_g3_d_1_1_g_app.html#abab9f0b6869c7654f7c71689878daa2b) covers it I think.

If the G3D documentation isn't clear, I'm sure @morgan3d would accept proposals for improving it.
