### ISSUE TITLE
Unnecessary setters

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#22]
There are several `set` routines in [App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp) that are only called from within this file to set private member fields. This could be accomplished simply by setting the variables instead of calling setters. Should these setters be removed? These include:

- [`setSceneBrightness()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L1254)
- [`setDisplayLatencyFrames()`](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L695)

**Comment by jspjutNV** [comment]
I assume these setters were created so the `Experiment` could safely set these values. I'm not sure the `Experiment` still sets these, or if they're only set up front. I'd prefer to remove these functions and just directly set the variables.

@joohwankimNV , are you okay with this simplification?

**Comment by bboudaoud-nv** [comment]
To provide a bit more detail, at least `setSceneBrightness()` is only every called with `m_sceneBrightness` as its argument, so this is effectively equivalent to `m_sceneBrightness = m_sceneBrightness`.

**Comment by jspjutNV** [comment]
Oh wow, so it seems like there was some confusion around `setSceneBrightness()` to begin with.

Maybe some version of the `ReactionExperiment` was using this in the past. I think for `abstract-fps` it's totally safe to remove.

**Comment by bboudaoud-nv** [comment]
Okay, planning to deal with both of these functions in one commit. Will leave a commented out line indicating where scene brightness was "set" before (even though it was always just re-assigned to identity).

**Comment by bboudaoud-nv** [comment]
These were removed as of [a recent commit](https://github.com/NVlabs/abstract-fps/commit/d75cdb505dc52b00810084df05a4cb72a86524bf), there is still a commented out line at [line 688 of App.cpp](https://github.com/NVlabs/abstract-fps/blob/master/target/source/App.cpp#L688) intended to capture where we had done this previously.
