### ISSUE TITLE
User config turn scale logging ignores session setting

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#226]
Currently we log the (per user) `cmp360` and `turnScale` values to the `Users` table in the database at the start/end of every session, but the per-session turn scale is not included in this value. 

Should we consider logging this as well/providing an "effective" cm/360° sensitivity (composite of all turn scales w/ sensitivity) in this/another table?

**Comment by jspjutNV** [comment]
Sounds like a useful feature to log all of this.
