### ISSUE TITLE
Initial Click to Spawn Target

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#25]
When you first open the application (playMode does not matter) and close the tab menu no target is spawned. In order to spawn the first red target you have to left click once. It seems as if this target should just appear without clicking, but I want to verify this before "fixing" the issue.

**Comment by bboudaoud-nv** [comment]
Looking a bit deeper here, it seems that this may be intentional. In the `Experiment::onInit()` we set the `m_app->presentationState`  to `PresentationState::initial` which seems to just wait for a click to move on to the next state...

**Comment by jspjutNV** [comment]
Yes, this was an intentional design decision. The text that appears prior to the first target is meant to instruct you how to being the experiment. If it's unclear we should fix that text. If the text blends in too much, maybe we should change the colors.

**Comment by bboudaoud-nv** [comment]
This makes sense, I strongly suggest we move away from the current text which is 

```
Aim at the target and shoot!
``` 

considering it does not prompt the user to click to spawn the first target. Perhaps we should elaborate a bit to something like:

```
Click to spawn the first target, then aim at the target and shoot!
```

**Comment by bboudaoud-nv** [comment]
Since this seems to be more related to how we communicate how to play to the user I am going to close this issue in favor of another issue regarding documenting player instructions.
