### ISSUE TITLE
Unicode degree symbol doesn't show correctly in user menu

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#250]
In code we use the unicode degree symbol `"°"` to represent degree units in the user menu. Unfortunately it seems these aren't necessarily represented correctly in the GUI window.

![image](https://user-images.githubusercontent.com/48839018/96616031-0fa68180-12d0-11eb-99a7-b7ea973af729.png)

We can either replace this with `"deg"` as we have in the past, or try to figure out the "right" way to use the degree symbol in G3D GUI windows.

**Comment by bboudaoud-nv** [comment]
Oddly this seems to not always show up as a problem. More investigation of the underlying cause of the incorrectly formatted symbol is needed before deciding on a fix.

**Comment by jspjutNV** [comment]
This was fixed in [7ded790e2f8992963c2f1a711101899cebe5ff39](https://github.com/NVlabs/abstract-fps/commit/7ded790e2f8992963c2f1a711101899cebe5ff39) by switching to `\xB0` for the degree symbol. Merged in #248 .
