### ISSUE TITLE
"Resume" button does not switch to mouse aiming mode

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#282]
When the "Resume" button is pressed, the mouse cursor remains visible, and mouse movement does not control the camera.

**Comment by bboudaoud-nv** [comment]
This is a bug introduced by removing control of the `FPSciApp`s mouse input mode from the `UserMenu::setVisible()` method. I think I can prop up a quick branch/PR to fix this w/ minimal code changes.
