### ISSUE TITLE
Walk Mode

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#36]
There are a number of issues that still occur/come up when `walkMode = True`. Some of these are listed below:

- The `PlayerEntity` definition in the scene `.Any` file needs to be removed when `walkMode=False` and added when `walkMode=True`, try to unify these to use a single scene
- Gravity/jump velocity seem to be correct, but the "zero" velocity seems very short (feels like hitting a ceiling)
- Depending on gravity settings climbing stairs can be possible/impossible without jumping, and there can sometimes be a tendency to "fall down" stairs without moving
- When setting a 0 `crouchHeight` in the `experimentconfig.Any` file the player still seems to be a bit above the ground

**Comment by jspjutNV** [comment]
I believe the `PlayerEntity` could be removed in code in that case. This issue is only a problem because the player model shows up in the first person view, right?

**Comment by bboudaoud-nv** [comment]
I don't think this is the right approach. `PlayerEntity` is used for the `PhysicsScene` collision detection, I would prefer to make `walkMode=False` still work w/ the `PlayerEntity` defined in the scene file. The visibility of the player model is always off (either we don't add it, or we set visibility false using `		m_scene->typedEntity<PlayerEntity>("player")->setVisible(false);`).

**Comment by bboudaoud-nv** [comment]
In addition the mouse continues to control view position when the tab menu is open. I believe this has to do with the `FirstPersonManipulator` that disables mouse interaction not being used when `walkMode=true`.

**Comment by bboudaoud-nv** [comment]
I realize we also probably broke mouse sensitivity when `walkMode=true`. We should go back and re-evaluate this.

**Comment by joohwankimNV** [comment]
Walking speed is faster when walking diagonally (e.g. pressing w and a together) than canonically (e.g. pressing only w or a). Maybe each direction is evaluated independently and results in sqrt(2) faster when moving diagonally?

**Comment by bboudaoud-nv** [comment]
Yes, this is an issue, see the source below for how the movement/translation is applied current (from App.cpp):
```
Vector3 linear = Vector3::zero();
linear += forward * ui->getY() * walkSpeed;
linear += right * ui->getX() * walkSpeed;
```
In order to fix this we should move to determining a (unit) direction vector from `[ui->getX(), ui->getY()]` then multiplying this by the walking speed to keep the velocity constant.

**Comment by bboudaoud-nv** [comment]
This has been fixed as of [a recent commit](https://github.com/NVlabs/abstract-fps/commit/e7c38d248ea4c050fb6d1c71d75e2aa5ccd1755c). The code now normalizes the walking direction before applying the `walkSpeed`.

```
// Get walking speed here (and normalize if necessary)
Vector3 linear = Vector3(ui->getX(), 0, -ui->getY());
if (linear.magnitude() > 0) {
	linear = linear.direction() * walkSpeed;
}
```

**Comment by bboudaoud-nv** [comment]
As an update to this issue we've addressed problems with differences in the scene file for `walkMode=False`, the only remaining issue affiliated with the scene file is that the player model is visible when `walkMode=False`. We've also resolved the issue with walking faster when holding multiple buttons and improved the jump values to make this feel a bit more realistic/normal.

### Remaining Issues
-
* Mouse sensitivity does not seem to do a good job of matching behavior from `FirstPersonManipulator`
* Haven't had time to look much into the crouch issue from above
* Can still struggle to climb/stay up stairs when on them
* Since there are no "windows" in the scene players can jump through holes in the scene and "fall forever"

**Comment by bboudaoud-nv** [comment]
* Matching `FirstPersonManipulator` was handled by removing a time dependence from the yaw (was never applied to pitch).
* The crouch issue seems related to the fact that the player "height" is set using a sphere intersection with the scene. The radius of this sphere effectively applies an offset to the crouch height. This can be "worked around" by setting a negative crouch height for now. In the future we probably want to set the sphere radius based on the `playerHeight` and then apply the crouch as relative to standing.
* The stair sliding might also have something to do w/ the spherical collision detection. Wil look into this shortly
* Holes in the scene can be closed by adding some invisible geometry to provide bounds

**Comment by bboudaoud-nv** [comment]
Per @pknowlesnv suggestion, we can add a `minHeight` field to the scene description so that the player is reset to a default position whenever their height is below this value.

**Comment by bboudaoud-nv** [comment]
[A recent commit](https://github.com/NVlabs/abstract-fps/commit/66778115a2a367fd6360a7fd4d3fe720c443164f) adds support for minimum height-based player location reset.

**Comment by bboudaoud-nv** [comment]
Since most of these issues have now been resolved and we've moved to `walkMode=True` as the default (removed the `walkMode` variable altogether) let's close this issue. We can create new issues for individual motion bugs at this point.
