### ISSUE TITLE
Hit detection be consistent with weapon dynamics

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#38]
Hit detection on player and target needs to be consistent with weapon type (projectile must be evaluated when it intersects with player/target).

**Comment by bboudaoud-nv** [comment]
I think that maybe `m_hitScan` was intended to toggle this behavior (instantaneous ray cast vs propagated projectile). I agree we should build in support for the projectile propagation and be able to use this for enemy --> player hit detection.
