### ISSUE TITLE
Cylinder target

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#39]
Add a new target shape, a cylinder. This represents the target shape in FPS games more realistically (standing figures).
Note that we want a black boundary as in our current sphere target.

**Comment by bboudaoud-nv** [comment]
We should make this `.Any` configurable by adding a `model` field to the `TargetConfig` similarly to how the `WeaponConfig` model is applied

**Comment by bboudaoud-nv** [comment]
A [recent commit](https://github.com/NVlabs/abstract-fps/commit/ce2b8bac414d75a93e4188ca75d13bd780908db3) adds support for arbitrary target models. I will close this issue for now, as the cylinder model can be supported. Issue #43 still deals with some naming issues regarding use of arbitrary `obj` files.
