### ISSUE TITLE
Player object for hit detection on player

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#41]
We need an object that represents the player for hit detection. This should be invisible in first person view. Maybe a transparent sphere or cylinder to begin with?

**Comment by bboudaoud-nv** [comment]
When `walkMode=True` we do use a player model (we need to in order to do valid collision detection). This model is as specified below.

``` playerModel = MD3Model::Specification { 
           defaultSkin = MD3Model::Skin("md3/crusader/models/players/Crusader/lower_default.skin", "md3/crusader/models/players/Crusader/upper_default.skin", "md3/crusader/models/players/Crusader/head_default.skin"); 
           directory = "md3/crusader/models/players/Crusader/"; 
        }; ````

**Comment by joohwankimNV** [comment]
Ah, ok. So the remaining job is hit detection not the player model. I think we can close this.
