### ISSUE TITLE
Field of view settings

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#46]
The field of view is currently set with horizontal field of view. Some people may want to set it vertically. Someone should add this option to the experiment config in a sensible way.

Note that we don't want destructive interference when the experiment config attempts to set both. It's almost certainly never going to be intentional to have the two settings fight.

**Comment by bboudaoud-nv** [comment]
I've updated the [`experimentconfig.Any`](https://github.com/NVlabs/abstract-fps/blob/master/target/data-files/SAMPLEexperimentconfig.Any) file to use a more descriptive label for this field `fieldOfView` --> `horizontalFieldOfView` and also updated the affiliated [readme](https://github.com/NVlabs/abstract-fps/blob/master/target/data-files/experimentConfigReadme.md) to better document conversion to vertical FoV.
