### ISSUE TITLE
Weapon cooldown indicator improvement

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#47]
The current weapon cooldown indicator is placed on the side of the screen and takes up a large portion of the field of view. Let's discuss and implement a change that more closely matches what is done in games.

Proposals I can think of are the following:

1. A circle around the aiming reticle that fills clockwise after each shot.
2. A weapon model that recoils

Are there other weapon cooldowns worth considering? I think 1) above may be the easiest since it's at a fixed location in screen space.

**Comment by jspjutNV** [comment]
I'm calling this a bug because the current implementation reduces the field of view. Fixing this will return us to full field of view.

**Comment by bboudaoud-nv** [comment]
We could also consider a cool down "bar" located above/below the ammo configuration. If we want to show the "cool down" in multiple ways I suggest adding a section to the design document.

**Comment by bboudaoud-nv** [comment]
"Full" field of view is restored as of a [recent commit](https://github.com/NVlabs/abstract-fps/commit/93718ca6b32575ad19d0fcb85672d1adfcdeeff4). Removed the bug tag for this reason.

**Comment by bboudaoud-nv** [comment]
Since there have been no additional comments since adding this feature I'm going to close the issue. Please re-open/create a new issue if the need is not met.
