### ISSUE TITLE
Latency box reduced size

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#48]
When the latency box is enabled, it currently consumes an entire vertical section of the screen. We should reduce the area consumed by this, and reduce the box size to work for the latency monitor placement we care about.

If someone is extra interested, we could add a control for latency box placement to the experiment config.

**Comment by bboudaoud-nv** [comment]
I believe that the latency box `size`, `position`, and possibly `boundary` (plus maybe even the color of this boundary?) should all be configured as part of either the `systemconfig.Any` (where the logger is setup) or in `experimentconfig.Any`. In addition if `hasLogger=false` in the `systemconfig.Any` we should automatically disable drawing this box.

We could also consider adding the "on" and "off" color values to this config (allows people to experiment w/ various GtG timings).

**Comment by bboudaoud-nv** [comment]
As of a [recent commit](https://github.com/NVlabs/abstract-fps/commit/93718ca6b32575ad19d0fcb85672d1adfcdeeff4) the click-to-photon (latency) box is more controllable from [`experimentconfig.Any`](https://github.com/NVlabs/abstract-fps/blob/master/target/data-files/experimentConfigReadme.md).

I believe this closes this issue for now.
