### ISSUE TITLE
Audio volume control

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#53]
We should add volume control for the audio as alluded to by #52

**Comment by bboudaoud-nv** [comment]
A [recent commit](https://github.com/NVlabs/abstract-fps/commit/307a33f329b96f24ae0eebbbd81fcb57d6b41cac) adds support for this w/ independent `explosionSoundVol` and `fireSoundVol` parameters in the `experimentconfig.Any` and `weaponconfig.Any` respectively.
