### ISSUE TITLE
More UI support for motion recording mode

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#57]
- A hot key to start/stop motion recording (we can record motion without opening user settings window, and also in full screen mode).
- Some indication that recording is happening (useful in full-screen mode). Maybe a line of sentence at the top.

**Comment by bboudaoud-nv** [comment]
As of now we have a recording indicator (top right of the screen) and use the `R` key to toggle recording. I will close this issue (can be re-opened if I'm missing something).
