### ISSUE TITLE
Access Violation on Shutdown

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#63]
There seems to be an exception thrown on shutdown (either via hitting the "close" button, using the minus key, or using the windowed close) related to destructing an `Array<TargetConfig>`. 

The call stack starts at the destructor call for `Array<TargetConfig>` and then points to the destructor for the `TargetConfig`, before pointing to an `Any` destructor/the `dropReference()` method within it.

**Comment by jspjutNV** [comment]
Do we know the last commit without this bug? I believe it was introduced as we were developing a solution to another problem.
