### ISSUE TITLE
Make all configs writable

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#65]
We'd like to be able to write out default configs from the default values set in the code rather than having `SAMPLE*config.Any` files that are copied as is currently done.

**Comment by jspjutNV** [comment]
I see this as lower priority since the current solution works which is why I set this to "defer"

**Comment by bboudaoud-nv** [comment]
I'm going to setup a list of config files here for progress monitoring:

- [ ] `startupconfig.Any`
- [ ] `systemconfig.Any`
- [ ] `userconfig.Any`
- [ ] `userstatus.Any`
- [ ] `experimentconfig.Any`

**Comment by bboudaoud-nv** [comment]
I would now say this issue is fully addressed, but want to wait for more testing/feedback from @jspjutNV  and @joohwankimNV before closing this for now.

**Comment by bboudaoud-nv** [comment]
I'm closing this issue since there hasn't been any feedback on insufficient implementation while using the new approach.
