### ISSUE TITLE
Collecting User Feedback in the Application

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#69]
@joohwankimNV mentioned that integrating some minimal user feedback via in-app "dialog"-style windows could be useful. @jspjutNV's current experiment could also benefit from this feature. I'm looking into what would be involved in adding this feature (including developing the G3D UI elements).

**Comment by bboudaoud-nv** [comment]
I can't seem to find a built-in dialog box style feature in G3D. Maybe @morgan3d knows about something that I'm missing. In the mean time I've developed a quick local solution for minimal dialogs that I will push shortly.

**Comment by morgan3d** [comment]
If you want a simple OS-level confirmation dialog, use guiPrompt(). For a
fully custom dialog, use GuiWindow() with the showModal() method.

-m

**Comment by bboudaoud-nv** [comment]
@joohwankimNV provided the following example for user feedback:

![image](https://user-images.githubusercontent.com/48839018/65977406-dccce980-e43f-11e9-8283-cb2c5b931aea.png)

The `Entry` and `MultipleChoice` boxes were already supported. I added a `Rating` type to deal with questions 2-3. I am looking into the possibility of using images as options as well.

Right now the approach is to split this "survey" into a series of discrete questions that we can then ask via separate dialogs. I can look into a unified form in the future, but giving the user enough control over this without making specification too complex is the big challenge.

**Comment by bboudaoud-nv** [comment]
This feature is currently "implemented" in as much as the questions above could be asked (less support for images). @joohwankimNV and @jspjutNV if you'd like to test this out feel free. For now I'm closing the issue.
