### ISSUE TITLE
TargetConfig::elevLocked parameter unused

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#70]
Currently the `elevationLocked` field is `.Any` configurable for the `TargetConfig` class (maps to the `elevLocked` boolean field). However, the only use of this flag in the application is in to/from `.Any` routines and in the `ExperimentConfig::printToLog()` method.

If we want to support `elevationLocked` we should document what it is intended to do and implement this behavior. Otherwise it would be a good idea to remove this flag for now to avoid misleading users in the future.

**Comment by jspjutNV** [comment]
@joohwankimNV do you have something you'd like `elevationLocked` to do? Otherwise, I suggest we remove the option.
