### ISSUE TITLE
Player Velocity Integration

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#73]
It seems that the player's desired (vertical) velocity is constantly integrating towards a larger value, even when the player is on a surface. Jumps clear/reset this velocity, so we don't notice during a jump, but when "falling off" a level component the change is quite noticeable.

We should move to a solution where the player's gravitational acceleration does not cause their desired -Y velocity to grow (i.e. standing on a surface sets this velocity to 0).

**Comment by bboudaoud-nv** [comment]
The [commit above](https://github.com/NVlabs/abstract-fps/commit/dfcd6b790485b0d930110c9902d7fc29a255ca21) adds an `m_inAir` flag to the `PlayerEntity`. Using this flag we attempt to track whether the player is in contact with a ground plane, and if so, stop the accumulation of velocity into the `m_lastJumpVelocity`. This _should_ prevent the asymmetry in walking off a surface vs jumping from the surface. This logic should be tested/reviewed thoroughly for issues.

**Comment by jspjutNV** [comment]
I couldn't fully understand the changes in the commit (dfcd6b7), but shouldn't this be fixable by just setting the vertical velocity to 0 whenever the player is in contact with ground?

**Comment by bboudaoud-nv** [comment]
Yes, this is effectively what is happening above. You need to do a few things:

1. Detect whether the player is "in air" based on:
  -  Whether or not they collide w/ anything
  - If they do collide, whether the majority of the collision normal is in the "+Y" (up) direction
2. Apply jump dynamics if in air, otherwise, just add a small (epsilon) negative velocity to keep the player (collision proxy) "in contact" with the floor
3. Make this work across simulation iterations and calls of `PlayerEntity::onSimulation()`

I believe all of this is now addressed. I agree that it could probably be written/documented more clearly. Certainly something worth continuing to look at in the future. We can always create another issue/code review to clean this up.

**Comment by bboudaoud-nv** [comment]
This implementation has been completed as far as I am concerned. [Other commits](https://github.com/NVlabs/abstract-fps/commit/0cfccb94422e9242bf9a2ad358b37e08abbcb950) have been made to help deal w/ some of the additional issues it has created. I am going to close this issue in favor of creating new (more descriptive) issues for the side-effects.
