### ISSUE TITLE
Improve Reported Time Stamp Precision

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#74]
Currently we are using a [GetLocalTime()](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlocaltime) call to get a [SYSTEMTIME](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-systemtime) structure that contains millisecond precision timestamps.

We'd like to improve this to capture microsecond (µs) precision timestamps. The logging format will not need to change, but the precision of the timing method needs to improve for this.

**Comment by bboudaoud-nv** [comment]
[This article](https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps) suggests using [GetSystemTimeAsPreciseFileTime()](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime?redirectedfrom=MSDN)  to get a 0.1µs precision [FILETIME](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime); however, I am struggling to find a good way to convert this into a [SYSTEMTIME](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-systemtime). The [FileTimeToSystemTime()](https://docs.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-filetimetosystemtime) method appears to be intended to do this, but appears to also come w/ loss of precision (truncation to ms).

**Comment by bboudaoud-nv** [comment]
The [commit above](https://github.com/NVlabs/abstract-fps/commit/8331b8965bc015f913fa0295d91b27dd4d2da6a7) uses `GetSystemTimeAsPreciseFileTime()` to build a microsecond-since-the-epoch value, then converts the majority of the timestamp to a `SYSTEMTIME` using the `FileTimeToSystemTime()` method mentioned above. The fractional seconds values from the `FILETIME` are used to populated the 6 digits after the decimal place in the seconds field.

**Comment by jspjutNV** [comment]
Does the `G3D::System:time()` not give an accurate enough timestamp? 

According to [the documentation](https://casual-effects.com/g3d/G3D10/build/manual/class_g3_d_1_1_system.html#acc67b3c1cb126362a011087171dba0a1) it should be as accurate as `getCycleCount()`

**Comment by jspjutNV** [comment]
Sounds like this is closed, but we might want to consider whether we should switch to the G3D time convention in the future. Closing the issue for now.
