### ISSUE TITLE
`Array<String>` should be replaced with storing data in inner loop

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#75]
In `Session.cpp` all of the record keeping functions prepare an `Array<String>` to store in the logger. These logger entries will eventually be consumed to create the log. This issue is to replace those `Array<String>` data members with `Array`s of the appropriate data type that is meant to be logged, probably through a new `struct` for each type of log.

The affected functions include the following:
* `Session::recordTrialResponse()`
* `Session::accumulateTrajectories()`
* `Session::accumulatePlayerAction(const String& action, const String& targetName)`
* `Session::accumulateFrameInfo(RealTime t, float sdt, float idt)`

**Comment by bboudaoud-nv** [comment]
A [recent commit](https://github.com/NVlabs/abstract-fps/commit/53a3436626b4f80ffd1f54676757668de06cc72e) adds support for structures/enums for handling this data storage where possible. I believe @pknowlesnv may try to move these structures into thread-safe queues to allow us to decouple writing logs from the main graphics thread.

**Comment by bboudaoud-nv** [comment]
Since these routines have been updated to work from structs I'll close this issue. We can/should open another issue to capture moving over logging routines and potentially decoupling the logger into its own thread.
