### ISSUE TITLE
Value of -1 not serializing from Any as Int

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#80]
It has been observed that when attempting to set a value of `-1` for the `respawnCount` field within the `TargetConfig` Any structure the value is not correctly serialized from the file.

Positive values for `respawnCount` serialize in just fine. This also doesn't seem to be an issue if the variable within the `TargetConfig` is changed from `int` to `float`.

In the short term we can move to a `float`/cast to get the value correct, but I'm creating this issue to track that this really should work for `int` types as well.

**Comment by jspjutNV** [comment]
Is it possible that `.Any` `int`s are actually `unsigned int`s?

**Comment by morgan3d** [comment]
Can you give me a minimal test case of this, like a main() with an Any in
it?

-m

**Comment by bboudaoud-nv** [comment]
@morgan3d a minimal reproducible example would be to include the following code in the `onInit()` for parsing a negative value into an `int`:

```
	int test = 0;

	AnyTableReader reader(PARSE_ANY(
		{
			value = -1
		}
	));

	reader.getIfPresent("value", test);
	logPrintf("\n\nValue = %d", test);
```

When line 5 is `value = 1` this prints `Value = 1` to the log.txt file, whereas when line 5 is `value = -1` (as shown above) this prints `Value = 0` to the log.txt (instead of the `Value = -1` we should get). The same appears to be true if `:` is used instead of `=` in the assignment.

If you'd like I can package this up into a project and send it along, but this should be enough to quickly reproduce the result.
