### ISSUE TITLE
`mouseEnabled` for `experimentConfig`

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#82]
Requesting for a way to enable/disable mouse motion. This feature can be used for a keyboard-only aiming training/testing scenario.

**Comment by bboudaoud-nv** [comment]
I believe the easiest way to do this is with a `mouseScale` parameter that lets the user sets a motion scale for X vs Y (horizontal vs vertical) view deflection. I can take a quick stab at introducing this via the `FpsConfig` structure.

We may also want to consider a key binds file in the future to allow experiment designers to developer new control schemes/button mapping without editing source.

**Comment by bboudaoud-nv** [comment]
Using the new `turnScale` parameter as a `Vector2` you can disable mouse-based turning in either the horizontal (`Vector2.x`) or vertical (`Vector2.y`) direction. If you would like no mouse motion at all you can set the value to `Vector2(0,0)`.

This should address this issue, so I'll close it now.
