### ISSUE TITLE
Saving user settings in the result db files.

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#84]
Let's save user settings in the result db files, which will make analysis easy. For now of particular interest to me are:
`cmp360`, `mouseDPI`, `reticleColor`, `reticleIndex`, `reticleScale`, `turnScale`.

**Comment by bboudaoud-nv** [comment]
How would we like to save these? I'm assuming a separate/new `User` table in the output database? Alternatively we could add these fields to the `Experiment` table which is currently fairly lightly used. 

Do we want to provide any support for the user changing settings during the trials (or is it implied that this has already happened by the time the experiment is taking place)? My guess is that for now we just report the user's setup at the start/end of the trial and hope/assume it hasn't changed inside (as a result of good experiment design).

**Comment by joohwankimNV** [comment]
Both `User` and `Experiment` tables sound good.

User settings need to be fixed during an experimental session, so I think we don't need to keep track of what happened during a session. In that sense, it's a great idea to record it at the start/end of a session to make sure this was the case. We can do at the start/end of a trial, but for now it seems a bit too verbose compared to our assumption.

**Comment by bboudaoud-nv** [comment]
For now let's stick with the single `Users` table entry that has been implemented. Note that the `Experiment` table still includes the subject ID. 

We currently add one entry to the `Users` table per session, but it should be easy enough to extend this to 2 to help detect changes. I'll go ahead and set this up for now. It shouldn't impact the database much compared with other entries. An alternative approach would be to just write the db once per session but with a `changed` field indicating if the UserConfig changed over the session.

**Comment by jspjutNV** [comment]
While we're talking about the `Users` table, it's worth noting that merging results `.db`s from many sessions would mean that there are multiple users in the table and that would be correct. We'd want a way to indicate which results in the other tables correspond with which user generated those results, so there should also be some reference to the `userID` key in other tables.

We might be getting to the point where creating a more formalized schema would be a good idea, but that would be a different related issue.

**Comment by bboudaoud-nv** [comment]
@jspjutNV, absolutely, I think we probably need a design doc-based discussion for the higher-level "merge-safe" database approach, then we can create some Github issues for the implementation work (if needed).

Adding a "Sessions" table (to replace "Experiments") is high on my list for now, as is finding a way to report conditions/parameters in a flexible way.

**Comment by bboudaoud-nv** [comment]
I believe the particular issue w/ logging user data in the database file is now resolved. We can open another issue for broader merge-safe database restructuring.
