### ISSUE TITLE
Database "Experiments" table update

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#85]
I believe the name for the `Experiments` table is misleading and should potentially be renamed to `Sessions`. This way it better represents what is actually in the table (certainly not intended to capture multiple experiments) and also can store improved/more useful information.

A (minimal) proposed row structure would look something like this:

|Session ID       | Timestamp                     |Subject ID              | Description                                |
|----------------|---------------------------|---------------------|-----------------------------------|
|The session ID |Time the session started |ID for the subject |Experiment desc + session desc |

Additional (optional) fields include:
* Stop timestamp or runtime
* Completed flag
* Trial counts
* Overall score metric
* Customizable session parameters (`reportList`)

If we agree that this change should be made we can implement it now with little overhead. I wanted to create a Git issue to track various changes in moving towards a merge-safe `Sessions` table.

**Comment by jspjutNV** [comment]
I support this renaming, though it does break backwards compatibility with a lot of data analysis scripts. It would make sense to have autogenerated database documentation to make it easier to maintain and update our data analysis scripts.

**Comment by bboudaoud-nv** [comment]
I agree, though currently I'm not sure we have any (formal) database documentation. Currently the bigger issue would be with tools like the Python importer, which rely on specific table/column names/locations. We could look into updating this (as well) automatically in the future, or rewriting the scripts to make more generic use of the database.

I think we should setup a meeting to discuss high-level reorganization of the FPSci results database. In the mean time I will start this renaming/reorg process in the FPSci repo and post commits/results relevant to this item here.

**Comment by bboudaoud-nv** [comment]
Since the core of this issue has been addressed I am closing it. We can open future items for more specific database updates.
