### ISSUE TITLE
Session change fails if scene reloading is needed AND targets are remaining

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#86]
Reporting a conditional failure of session change. The conditions for this failure is:
1. Session change involves change in scene. Specifically, `sceneName` for the chosen session is different from the current session.
2. There is a target remaining in the current session. Doesn't matter if it's a reference target or in-task target.

A simple procedure for recreating this behavior:
1. Start the app, and start a session.
2. Make a click. This will pop up the reference target.
3. Without destroying the reference target, change session to one containing a scene that's different than the current one.

The exception (in case of failure) occurs in the function `App::destroyTarget(int index)`, while executing command `targetArray.fastRemove(index);`.

**Comment by bboudaoud-nv** [comment]
@joohwankimNV this recent commit should fix the issue you were seeing, feel free to test it out on your example setup and close this issue if it is working.

**Comment by bboudaoud-nv** [comment]
I believe this is now resolved. Closing this issue.
