### ISSUE TITLE
Refactor/Remove playMode from startupconfig.Any

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#89]
Currently `playMode=false` is a bit overloaded and does many things including:

- Controlling whether the app runs in windowed or fullscreen mode
  - Modifies the default window height/aspect ratio for windowed mode
- Controlling whether the app is drawn with the developer window
- Controlling whether the app draws its own debug menu (file ribbon-style menu)
- Controlling whether the additional on-screen menus can be opened/modified
  - Render controls, Player controls, Weapon controls, Waypoint manager

This is an issue to track splitting up this functionality and improving `startupconfig.Any` and/or the in-app menu system as needed.

**Comment by bboudaoud-nv** [comment]
The most recent commit (see above) adds support for a separate `fullscreen` (boolean) parameter in `startupconfig.Any` that allows the user to control fullscreen vs windowed mode separately from `playMode=false`. Documentation has been updated to reflect this.

**Comment by bboudaoud-nv** [comment]
@jspjutNV or @joohwankimNV  do we want to make waypoint editing a special "mode" for the application? We could choose to just have another `startupconfig.Any` boolean parameter that controls `waypointEditorMode`. Let me know if you think this makes sense, or if it should just stay in `playMode=false` for now.

**Comment by bboudaoud-nv** [comment]
My suggestion is that we consider renaming the existing `playMode` parameter to something more descriptive like `developerMode` (w/ inverted function) then add (at least) 1 new control flag (`waypointEditorMode`) which is conditional on `developerMode` as well. The idea is that the user sets `developerMode=true`  when they want access to more in-game settings (i.e. the render, player, and weapon windows, as well as the normal G3D debug window). If beyond normal developer mode, the user wants to edit waypoints for paths then they set `waypointEditorMode=true` which enables the waypoint config menu and the key binds for editing waypoints. 

If `developerMode=false` then the state of `waypointEditorMode` is not considered. If we want an even finer granularity control over the experience we could always make the use of each window conditional on its own flag within a sub-structure in the `startupconfig.Any` file. In this case we'd have something more like this:

```
{
     experimentConfigPath = "";
     userConfigPath = "";
     fullscreen = true;
     showWindows = {
          debug = true;
          developer = true;
          renderControls = true;
          playerControls = false;
          weaponControls = false;
          waypointControls = false;
     };
}
```

**Comment by bboudaoud-nv** [comment]
The [previous commit](https://github.com/NVlabs/abstract-fps/commit/40c16100a3daa0d13641f49fe48719dd8c69c838) implements the **Simple Solution** referenced in my previous comment. If we'd like to add more fields we can, but for now I think this is likely sufficient and we can close the issue if others agree.

**Comment by jspjutNV** [comment]
I agree with the changes from commit 40c1610 and I believe they solve this issue in combination with the earlier split for `fullscreen` having an independent control. I'm closing this, but we should keep an eye out to make sure the functionality matches the expectations.
