### ISSUE TITLE
1920x1080 resolution assumption(s)

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#91]
There are several places in code where we imply that the user has a 1920 x 1080 monitor, though this is not documented as a requirement for FPSci currently. A few examples of places where this assumption is made (in code) include:

- Mouse sensitivity conversion (used as a sort of "magic number")
- 2D element compositing (used to scale elements for window resize)
- Window sizing for fullscreen/windowed mode (uses hard coded constants)
- In the `ScreenSetting` struct included in `App.h` (does not appear to be used)

It is worth noting that the `SystemConfig::load()` method already determines the displays X/Y resolution (`displayXRes`/`displayYRes`) in `onInit()` so we can detect the resolution/aspect ratio if we want to make this dynamic.

Fortunately 2D (i.e. HUD) element positions are primarily based on the `RenderDevice` size and have been (mostly) tested to work. To test this on a machine that has a 1920 x 1080 monitor, simply run the application with `fullscreen=false` in `startupconfig.Any` and resize the window using the cursor.

We should have more discussion about how we want to deal with this, and whether we'd like to document/recommend a range of resolution/aspect ratio for running FPSci.

**Comment by jspjutNV** [comment]
The magic number for mouse sensitivity may not actually come from the 1080p monitor resolution. I didn't test other resolutions to see if the mouse sensitivity setting changes the behavior of that scaling. I suspect the scaling isn't resolution dependent, but we'll need to test to verify.

**Comment by bboudaoud-nv** [comment]
Merging of #121 and #124 addressed (what seemed to be an incorrect) use of 1920 for mouse sensitivity here. There is still several use of hard-coded `1920`/`1080` that are used for viewport-based scaling. These should probably be moved over the display resolution values from the `SystemConfig`.

Remaining uses include:
- `1920` used for 1D scale in `App::onPostProcessHDR3DEffects()`
- `1920` and `1080` used for 2D scale in `App::drawHUD()`
- `1920` used for 1D scale in `App::onGraphics2D()`
- `1920` and `1080` in `main()` used for window sizing in full-screen
- `1920` and `1080` used in (depricated) `ScreenSetting` in `App.h`
