### ISSUE TITLE
Visual feedback of hit/miss

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/abstract-fps#96]
Currently we have the following feedback for player-world interaction.
- Firing sound when hitscan weapon is fired.
- Explosion animation / sound when target is cleared.

We have been seeing requests from our subjects to include more feedback signals. They include:
- More audio feedback for the following events.
    - Firing sound for tracking weapon. ("wewwwwwwwwwww ...")
    - Target got hit but not cleared yet. Repeat rapidly for tracking weapon. ("ting ting ting ting ...")
    - Wall is hit. Repeat rapidly for tracking weapon. ("bzzzzzzzzzzz ...")
- More visual feedback for the following events.
    - Target got hit but not cleared yet. Small spark animations.
    - Wall is hit while using tracking weapon (tracking equivalent of decals). Some trailing impression such as scorch would be good. We may also apply the spark animation on the wall as well.

**Comment by jspjutNV** [comment]
I'm splitting this into Visual hit confirmation (this issue), target hit sound (#98 ) and rapid fire sound(#99 ).

The visual hit confirmation on hard surfaces is usually decals (like we already have) and some sort of particle system. I believe that there exists a G3D sample that does some sort of particle simulation, but we would probably be fine to spawn a few "spark" objects and have them move away from the hit target. Perhaps this spark texture should be specified per target.

**Comment by bboudaoud-nv** [comment]
Audio feedback should now be developed (see the `hitSound(Vol)` and `destroyedSound(Vol)` in the `TargetConfig` structure. We should discuss visual feedback further before implementation here.

**Comment by joohwankimNV** [comment]
A related minor feature request for future discussion - ability to configure the size of decals.

**Comment by bboudaoud-nv** [comment]
I've moved miss decal scale into its own issue for discussion (see #100). Let's keep this issue focused on the list in the original post for now and create new issues for additional requests as they come up.

**Comment by bboudaoud-nv** [comment]
As of now everything except the target "sparks" and wall scorch marks should be implemented. I will take a first pass at a version of this sometime shortly and report back here/reference this issue in the commit message(s).

**Comment by bboudaoud-nv** [comment]
Continuous fire weapon (i.e. laser) miss decals are supported as of a [recent commit](https://github.com/NVlabs/abstract-fps/commit/9df1fd8f5df23ea899a72f693902ee81de487c53). 

I have drafted a basic "hit decal" (i.e. "sparks") in a [new branch](https://github.com/NVlabs/abstract-fps/tree/HitDecal). This should be reviewed in place before I issue the merge request back to `master`.

Once both features are approved we can close this issue.

**Comment by bboudaoud-nv** [comment]
I believe this has been done as of [this commit](https://github.com/NVlabs/abstract-fps/commit/07d6e63b86e912eaf11b4c4f97c75ce1774c6184). Closing this issue.
