### ISSUE TITLE
Invalid default Experiment/UserConfig Files

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/abstract-fps#97]
Currently the application hits an exception if the "default" `experimentconfig.Any` and `userstatus.Any` (i.e. the files written automatically when none are present on disk) are used as-is. This results in a fresh clone/build of the repo resulting in exception messages. This is due to several issues w/ the default config files generated:

- In `userstatus.Any` the default `sessions` Array(s) are empty (no sessions to load)
- In `experimentconfig.Any` the default `sessions` and `targets` Arrays are empty (no sessions to reference)

Several possible solutions include:
1. Checking in valid "default" config files (located in `data-files/` so that a fresh clone runs some default experiment w/o a change in code. If these files were deleted the issue described above would reoccur with the same files being generated in the application.
2. Checking in valid "default"/"example" config files (as described above) in a directory other than `data-files` and pointing to them with documentation. 
3. Changing the `ConfigFiles.h` default values to include session(s) for the `userconfig.Any` file and matching session(s) and target(s) for the `experimentconfig.Any` file.

Generally speaking it makes sense for a user who just cloned the repo for the first time to be able to quickly get it up and running without a need for copy-over of (valid/pre-designed) config files from another location.

**Comment by joohwankimNV** [comment]
Nvidia developers only: [Design doc](https://docs.google.com/document/d/1GFYOCxbZTSnZQSxMyMvXSxQLhzVDsBliIiRVajxz5vY/edit?usp=sharing) to discuss about the default configuration.

**Comment by jspjutNV** [comment]
I'm somewhat indifferent to how this is implemented, as long as the implementation is sensible. What makes the most sense to me is having the default config loaded when no config is provided include some default target types and at least one session that uses that one or more target type.

**Comment by bboudaoud-nv** [comment]
Based on feedback from Joohwan in the design doc I will be implementing a simple default set of targets (`"static"`, `"moving"`, and `"jumping"`) together with 2 simple example sessions (`"60Hz"` and `"30Hz"`). Look for a commit shortly. We can work on feedback from there.

**Comment by bboudaoud-nv** [comment]
In addition to the commit above, it makes sense not to serialize out the default field values (this overcrowds the files and makes it difficult to read what exactly is changed). I think I'm going to add a mechanism to remove default values from config files to keep them minimal.

**Comment by bboudaoud-nv** [comment]
I believe all requests have now been filled. Currently the 3 (previously mentioned) targets are created along with the `30Hz` and `60Hz` sessions. The targets have been switched to `destSpace = "player"` to keep them working across the widest possible variety of scenes. 

If there are no further comments we can close this issue.

**Comment by joohwankimNV** [comment]
Agreed, closing!
