### ISSUE TITLE
Target hit sound

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/abstract-fps#98]
As identified by @joohwankimNV in (#96 ), we should include audio feedback when targets or walls are hit. Right now, targets only produce a sound when they are destroyed. We should add a hit sound when target is hit. Typical sound for this kind of event in shipping games is a soft "ding" sound.

An extra feature that could be useful, but maybe not required yet is the ability to specify a "headshot" sound which plays for a different target or part of a target. I recommend for now that this target hit sound should be associated with the target and not the weapon.

**Comment by bboudaoud-nv** [comment]
This is fairly easy to implement, I'll take care of it shortly. For now the default `hitSound` will be `18397__inferno__smalllas.wav` from G3D, but we can always replace this in the future.

Per (offline) discussion w/ Josef we are also going to add a `sceneHitSound` field to the `experimentconfig.Any`. This should allow the user to specify an additional sound file to use when the scene, but not the skybox, is hit with a round.
